---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-yaml
          - id: check-json
          - id: check-toml
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: name-tests-test
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.38.0
      hooks:
          - id: markdownlint-fix

    - repo: https://github.com/codespell-project/codespell
      rev: v2.2.6
      hooks:
          - id: codespell
            exclude: ^poetry.lock$

    - repo: https://github.com/crate-ci/typos
      rev: v1.16.25
      hooks:
          - id: typos

    - repo: https://github.com/pappasam/toml-sort
      rev: v0.23.1
      hooks:
          - id: toml-sort-fix

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, --config-file=.yamllint]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt

    - repo: https://github.com/mrtazz/checkmake.git
      rev: 0.2.2
      hooks:
          - id: checkmake

    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
          - id: nbstripout

    - repo: https://github.com/nbQA-dev/nbQA
      rev: 1.7.1
      hooks:
          - id: nbqa-flake8
          - id: nbqa-black
          - id: nbqa-isort
          # - id: nbqa-mypy
          # - id: nbqa-pylint
          # - id: nbqa-pydocstyle
          - id: nbqa-ruff
            args: [--fix]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.8
      hooks:
          - id: ruff
            args: [--config, pyproject.toml]

    - repo: https://github.com/myint/autoflake
      rev: v2.2.1
      hooks:
          - id: autoflake
            args: [--remove-all-unused-imports, --remove-unused-variables, --in-place, --exclude=__init__.py]

    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies:
                - flake8-bugbear
                - flake8-comprehensions
                - flake8-docstrings
                - flake8-import-order
                - flake8-bandit
                - flake8-annotations
                - mccabe


    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--profile, black]

    - repo: https://github.com/psf/black
      rev: 23.12.0
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.7.1
      hooks:
          - id: mypy
            args: [--ignore-missing-imports]


    - repo: https://github.com/PyCQA/pydocstyle
      rev: 6.3.0
      hooks:
          - id: pydocstyle

    - repo: https://github.com/myint/docformatter
      rev: v1.7.5
      hooks:
          - id: docformatter
            args: [--in-place]


    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.6
      hooks:
          - id: bandit

    - repo: https://github.com/python-poetry/poetry
      rev: 1.7.0
      hooks:
          - id: poetry-check
          - id: poetry-lock


# コマンド一覧
# poetry run pre-commit run --all-files　で実行
# pre-commit autoupdate　で更新
